PROGRAM START
IGNORE  EXPONENT CALCULATOR
IGNORE
PRINT EXPONENT CALCULATOR
PRINT PLEASE USE WHOLE NUMBERS ONLY
PROMPT # "BASE: "
SET #BASE &LAST
PROMPT # "EXPONENT: "
SET #EXP &LAST
SET #TOTAL 1
SET #X 0
WHILE LESSER #X #EXP
MULT #TOTAL #BASE
SET #TOTAL &LAST
ADD #X 1
SET #X &LAST
WHEND
PRINT "YOUR TOTAL IS: " #TOTAL
PROGRAM STOP